Repository wisemen-digital/node-core, pull requests merged in 2025-01, with the labels that each got.

#18 pgBoss NestJS job
  packages/pgboss-nestjs-job/.release-it.json
  packages/pgboss-nestjs-job/README.md
  packages/pgboss-nestjs-job/lib/client/pgboss-client.module.ts
  packages/pgboss-nestjs-job/lib/client/pgboss-client.ts
  packages/pgboss-nestjs-job/lib/index.ts
  packages/pgboss-nestjs-job/lib/jobs/job-serialization.type.ts
  packages/pgboss-nestjs-job/lib/jobs/job.abstract.ts
  packages/pgboss-nestjs-job/lib/jobs/job.decorator.ts
  packages/pgboss-nestjs-job/lib/jobs/job.module.ts
  packages/pgboss-nestjs-job/lib/jobs/job.registry.ts
  packages/pgboss-nestjs-job/lib/persistence/archive.entity.ts
  packages/pgboss-nestjs-job/lib/persistence/job-state.enum.ts
  packages/pgboss-nestjs-job/lib/persistence/job.entity.ts
  packages/pgboss-nestjs-job/lib/scheduler/pgboss-scheduler.module.ts
  packages/pgboss-nestjs-job/lib/scheduler/pgboss-scheduler.service.ts
  packages/pgboss-nestjs-job/lib/worker/constants.ts
  packages/pgboss-nestjs-job/lib/worker/pgboss-worker.config.ts
  packages/pgboss-nestjs-job/lib/worker/pgboss-worker.module.ts
  packages/pgboss-nestjs-job/lib/worker/pgboss-worker.thread.ts
  packages/pgboss-nestjs-job/lib/worker/pgboss-worker.ts
  packages/pgboss-nestjs-job/package.json
  packages/pgboss-nestjs-job/tsconfig.json
  pnpm-lock.yaml
Labels: 📃 XL PR

#19 Node doc processor@0.1.0
  packages/node-doc-processor/.release-it.json
  packages/node-doc-processor/README.md
  packages/node-doc-processor/lib/index.ts
  packages/node-doc-processor/lib/jobs/generate-pdf-from-url/generate-pdf-from-url.data.ts
  packages/node-doc-processor/lib/jobs/generate-pdf-from-url/generate-pdf-from-url.job.ts
  packages/node-doc-processor/lib/jobs/generate-pdf-from-url/index.ts
  packages/node-doc-processor/lib/jobs/index.ts
  packages/node-doc-processor/lib/jobs/merge-pdf/index.ts
  packages/node-doc-processor/lib/jobs/merge-pdf/merge-pdf.data.ts
  packages/node-doc-processor/lib/jobs/merge-pdf/merge-pdf.job.ts
  packages/node-doc-processor/lib/types/enums/index.ts
  packages/node-doc-processor/lib/types/enums/page-format.enum.ts
  packages/node-doc-processor/lib/types/enums/page-orientation.enum.ts
  packages/node-doc-processor/lib/types/index.ts
  packages/node-doc-processor/lib/types/queue-name.ts
  packages/node-doc-processor/package.json
  packages/node-doc-processor/tsconfig.json
Labels: 📃 S PR

#20 Pgboss nestjs job@0.1.0
  packages/node-doc-processor/.release-it.json
  packages/node-doc-processor/README.md
  packages/node-doc-processor/lib/index.ts
  packages/node-doc-processor/lib/jobs/generate-pdf-from-url/generate-pdf-from-url.data.ts
  packages/node-doc-processor/lib/jobs/generate-pdf-from-url/generate-pdf-from-url.job.ts
  packages/node-doc-processor/lib/jobs/generate-pdf-from-url/index.ts
  packages/node-doc-processor/lib/jobs/index.ts
  packages/node-doc-processor/lib/jobs/merge-pdf/index.ts
  packages/node-doc-processor/lib/jobs/merge-pdf/merge-pdf.data.ts
  packages/node-doc-processor/lib/jobs/merge-pdf/merge-pdf.job.ts
  packages/node-doc-processor/lib/types/enums/index.ts
  packages/node-doc-processor/lib/types/enums/page-format.enum.ts
  packages/node-doc-processor/lib/types/enums/page-orientation.enum.ts
  packages/node-doc-processor/lib/types/index.ts
  packages/node-doc-processor/lib/types/queue-name.ts
  packages/node-doc-processor/package.json
  packages/node-doc-processor/tsconfig.json
Labels: 📃 S PR

#21 node-doc-processor - Add documentation
  packages/node-doc-processor/README.md
  packages/node-doc-processor/package.json
Labels: 📃 XS PR

#24 hobs to jobs
  packages/pgboss-nestjs-job/README.md
Labels: 📃 XS PR, 🛠️ bugfix
