Repository wisemen-digital/node-core, pull requests merged in 2025-03, with the labels that each got.

#28 feat: rework job data
  packages/pgboss-nestjs-job/lib/index.ts
  packages/pgboss-nestjs-job/lib/jobs/base-job.ts
  packages/pgboss-nestjs-job/lib/jobs/job-handler.ts
  packages/pgboss-nestjs-job/lib/jobs/job-serialization.type.ts
  packages/pgboss-nestjs-job/lib/jobs/job.abstract.ts
  packages/pgboss-nestjs-job/lib/jobs/job.decorator.ts
  packages/pgboss-nestjs-job/lib/jobs/job.registry.ts
  packages/pgboss-nestjs-job/lib/jobs/serialized-job.ts
  packages/pgboss-nestjs-job/lib/scheduler/pgboss-scheduler.service.ts
  packages/pgboss-nestjs-job/lib/worker/constants.ts
  packages/pgboss-nestjs-job/lib/worker/pgboss-worker.thread.ts
  packages/pgboss-nestjs-job/lib/worker/pgboss-worker.ts
Labels: 📃 S PR, ✨ feature

#30 Feature/add monetary readme
  .gitignore
  packages/monetary/README.md
  packages/monetary/eslint.config.js
  packages/monetary/lib/currency.enum.ts
  packages/monetary/lib/illegal-monetary-operation.error.ts
  packages/monetary/lib/index.ts
  packages/monetary/lib/monetary-amount.column.ts
  packages/monetary/lib/monetary.column.ts
  packages/monetary/lib/monetary.dto.ts
  packages/monetary/lib/monetary.find-operator.ts
  packages/monetary/lib/monetary.object.ts
  packages/monetary/lib/monetary.ts
  packages/monetary/lib/monetary.validator.ts
  packages/monetary/lib/precision-loss-error.ts
  packages/monetary/lib/tests/monetary.unit.test.ts
  packages/monetary/lib/tests/monetary.validator.test.ts
  packages/monetary/lib/unsupported-currency-error.ts
  packages/monetary/package.json
  pnpm-lock.yaml
Labels: 📃 XL PR, ✨ feature

#31 Add min amount to monetary
  packages/monetary/lib/monetary.validator.ts
  packages/monetary/lib/tests/monetary.validator.test.ts
Labels: 📃 XS PR, ✨ feature

#32 Add comparison methods
  packages/monetary/lib/monetary.ts
  packages/monetary/lib/tests/monetary.unit.test.ts
Labels: 📃 S PR, ✨ feature

#35 added max amount
  packages/monetary/lib/monetary.validator.ts
  packages/monetary/lib/tests/monetary.validator.test.ts
Labels: 📃 XS PR, ✨ feature

#36 bugfix where undefined values are not correctly validated but throws error instead
  packages/monetary/lib/monetary.validator.ts
  packages/monetary/lib/tests/monetary.validator.test.ts
Labels: 📃 S PR, 🛠️ bugfix

#37 fix: update validation to handle null values for monetaryDto
  packages/monetary/lib/monetary.validator.ts
Labels: 📃 XS PR, 🛠️ bugfix

#38 Chore/doc processor update packages
  packages/node-doc-processor/README.md
  packages/node-doc-processor/lib/jobs/generate-pdf-from-url/generate-pdf-from-url.job.ts
  packages/node-doc-processor/lib/jobs/merge-pdf/merge-pdf.job.ts
  packages/node-doc-processor/package.json
  pnpm-lock.yaml
Labels: 📃 XS PR
